// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG8ZbkpFa5VZGeOOnPauZfBTt8lUP8tyo',
    appId: '1:704868357629:web:0379dbadf2ab209ff63594',
    messagingSenderId: '704868357629',
    projectId: 'flut-db-kenny',
    authDomain: 'flut-db-kenny.firebaseapp.com',
    storageBucket: 'flut-db-kenny.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1SkfGF88hsZ5h3JGUxomxjftSUntZo4',
    appId: '1:704868357629:android:5a04ab0c85900dadf63594',
    messagingSenderId: '704868357629',
    projectId: 'flut-db-kenny',
    storageBucket: 'flut-db-kenny.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkLzw6uvdxYJrrXXnvvWkaP3PnwVb4JPI',
    appId: '1:704868357629:ios:04ef952a134b1785f63594',
    messagingSenderId: '704868357629',
    projectId: 'flut-db-kenny',
    storageBucket: 'flut-db-kenny.firebasestorage.app',
    iosBundleId: 'com.example.flutdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkLzw6uvdxYJrrXXnvvWkaP3PnwVb4JPI',
    appId: '1:704868357629:ios:04ef952a134b1785f63594',
    messagingSenderId: '704868357629',
    projectId: 'flut-db-kenny',
    storageBucket: 'flut-db-kenny.firebasestorage.app',
    iosBundleId: 'com.example.flutdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG8ZbkpFa5VZGeOOnPauZfBTt8lUP8tyo',
    appId: '1:704868357629:web:8325aec20ad2c36af63594',
    messagingSenderId: '704868357629',
    projectId: 'flut-db-kenny',
    authDomain: 'flut-db-kenny.firebaseapp.com',
    storageBucket: 'flut-db-kenny.firebasestorage.app',
  );
}
